from __future__ import annotations

"""Arabic-first and English branded PDF report generator using fpdf2."""

import io
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from fpdf import FPDF

from analytics.schemas import KPICard, ReportResult
from core.logging_setup import get_logger

logger = get_logger(__name__)

FONTS_DIR = Path(__file__).parent.parent / "assets" / "fonts"

REPORT_TITLES: dict[str, tuple[str, str]] = {
    "sales_overview": ("نظرة عامة على المبيعات", "Sales Overview"),
    "top_products": ("أفضل المنتجات", "Top Products"),
    "slow_inventory": ("المخزون بطيء الحركة", "Slow-Moving Inventory"),
    "receivables_aging": ("تقادم الذمم المدينة", "Receivables Aging"),
    "expense_breakdown": ("تفصيل المصروفات", "Expense Breakdown"),
}


class PDFReportDocument(FPDF):
    """Custom FPDF document with branded headers, footers, and font configuration."""

    def __init__(
        self,
        app_name: str = "REMO_OX Analytics",
        report_title: str = "",
        language: str = "ar",
    ) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self.app_name = app_name
        self.report_title = report_title
        self.language = language
        self.set_auto_page_break(auto=True, margin=15)

        # Register Amiri Arabic font
        regular_font = FONTS_DIR / "Amiri-Regular.ttf"
        bold_font = FONTS_DIR / "Amiri-Bold.ttf"

        if regular_font.exists():
            self.add_font("Amiri", "", str(regular_font))
            self.has_amiri = True
        else:
            self.has_amiri = False

        if bold_font.exists():
            self.add_font("Amiri", "B", str(bold_font))

        self.active_font = "Amiri" if self.has_amiri else "Helvetica"

    def header(self) -> None:
        """Render branded header bar on each page."""
        self.set_font(self.active_font, "B", 10)
        self.set_text_color(27, 79, 114)  # #1B4F72 Brand primary

        align_app = "R" if self.language == "ar" else "L"
        align_title = "L" if self.language == "ar" else "R"

        self.cell(95, 8, self.app_name, align=align_app)
        self.set_font(self.active_font, "", 9)
        self.set_text_color(100, 116, 139)
        self.cell(95, 8, self.report_title, align=align_title, new_x="LMARGIN", new_y="NEXT")

        # Divider line
        self.set_draw_color(226, 232, 240)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self) -> None:
        """Render footer with page numbers and confidentiality notice."""
        self.set_y(-15)
        self.set_font(self.active_font, "", 8)
        self.set_text_color(148, 163, 184)

        page_str = (
            f"صفحة {self.page_no()} من {{nb}}"
            if self.language == "ar"
            else f"Page {self.page_no()} of {{nb}}"
        )
        confidential_str = (
            "تقرير تحليلي سري - تم إنشاؤه بواسطة REMO_OX Analytics"
            if self.language == "ar"
            else "Confidential Analytics Report — Generated by REMO_OX Analytics"
        )

        align_conf = "R" if self.language == "ar" else "L"
        align_page = "L" if self.language == "ar" else "R"

        self.cell(100, 10, confidential_str, align=align_conf)
        self.cell(90, 10, page_str, align=align_page)


class PDFReportGenerator:
    """Service generating formatted, downloadable PDF reports."""

    def __init__(
        self,
        app_name: str = "REMO_OX Analytics",
        brand_color_hex: str = "#1B4F72",
    ) -> None:
        self.app_name = app_name
        self.brand_color_hex = brand_color_hex

    def generate_report_pdf(
        self,
        report: ReportResult,
        language: str = "ar",
        chart_png_bytes: bytes | None = None,
    ) -> bytes:
        """Assemble full PDF report document from ReportResult."""
        ar_title, en_title = REPORT_TITLES.get(report.report_id, (report.report_id, report.report_id))
        title = ar_title if language == "ar" else en_title

        pdf = PDFReportDocument(
            app_name=self.app_name,
            report_title=title,
            language=language,
        )
        pdf.alias_nb_pages()
        pdf.add_page()

        # Report Heading
        pdf.set_font(pdf.active_font, "B", 18)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 12, title, align="R" if language == "ar" else "L", new_x="LMARGIN", new_y="NEXT")

        # Timestamp & Meta
        now_str = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
        date_label = f"تاريخ التقرير: {now_str}" if language == "ar" else f"Generated: {now_str}"
        pdf.set_font(pdf.active_font, "", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 6, date_label, align="R" if language == "ar" else "L", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # KPI Summary Grid
        if report.kpis:
            self._render_kpi_grid(pdf, report.kpis, language)
            pdf.ln(5)

        # Embedded Chart
        if chart_png_bytes:
            pdf.ln(3)
            img_buf = io.BytesIO(chart_png_bytes)
            # Center image on page: width = 170mm (210 - 20 margin = 190 max)
            pdf.image(img_buf, x=20, w=170)
            pdf.ln(8)

        # Data Tables
        if report.tables:
            for table_name, tool_res in report.tables.items():
                self._render_table(pdf, table_name, tool_res, language)
                pdf.ln(6)

        # Calculation Formula Note
        if report.calculation_description:
            self._render_calculation_note(pdf, report.calculation_description, language)

        return bytes(pdf.output())

    def _render_kpi_grid(self, pdf: PDFReportDocument, kpis: list[KPICard], language: str) -> None:
        """Render KPI cards in a 2-column grid."""
        pdf.set_font(pdf.active_font, "B", 12)
        pdf.set_text_color(27, 79, 114)
        sec_title = "المؤشرات الرئيسية للأداء" if language == "ar" else "Key Performance Indicators"
        pdf.cell(0, 8, sec_title, align="R" if language == "ar" else "L", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        card_w = 90
        card_h = 20

        for i in range(0, len(kpis), 2):
            pair = kpis[i : i + 2]
            y_start = pdf.get_y()

            for j, card in enumerate(pair):
                x_pos = 10 + (j * 95)
                pdf.set_xy(x_pos, y_start)

                # Card box background & border
                pdf.set_fill_color(248, 250, 252)
                pdf.set_draw_color(226, 232, 240)
                pdf.rect(x_pos, y_start, card_w, card_h, style="DF")

                # Card Label
                pdf.set_xy(x_pos + 4, y_start + 3)
                pdf.set_font(pdf.active_font, "", 9)
                pdf.set_text_color(100, 116, 139)
                pdf.cell(card_w - 8, 5, card.label, align="R" if language == "ar" else "L")

                # Card Value & Delta
                pdf.set_xy(x_pos + 4, y_start + 9)
                pdf.set_font(pdf.active_font, "B", 12)
                pdf.set_text_color(30, 41, 59)
                val_text = f"{card.value}" + (f" ({card.delta})" if card.delta else "")
                pdf.cell(card_w - 8, 7, val_text, align="R" if language == "ar" else "L")

            pdf.set_y(y_start + card_h + 3)

    def _render_table(
        self,
        pdf: PDFReportDocument,
        title: str,
        tool_res: Any,
        language: str,
    ) -> None:
        """Render structured data table with headers and row zebra styling."""
        if not tool_res.data:
            return

        pdf.set_font(pdf.active_font, "B", 11)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 8, title, align="R" if language == "ar" else "L", new_x="LMARGIN", new_y="NEXT")

        cols = getattr(tool_res, "columns", None) or (list(tool_res.data[0].keys()) if tool_res.data else [])
        display_cols = cols[:6]
        col_w = 190 / len(display_cols)

        # Table Header
        pdf.set_fill_color(27, 79, 114)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font(pdf.active_font, "B", 9)

        align = "R" if language == "ar" else "L"
        for col in display_cols:
            pdf.cell(col_w, 7, str(col), border=1, fill=True, align=align)
        pdf.ln()

        # Rows (limit to top 20 rows in PDF)
        pdf.set_font(pdf.active_font, "", 8)
        pdf.set_text_color(30, 41, 59)

        for row_idx, row in enumerate(tool_res.data[:20]):
            fill_color = 255 if row_idx % 2 == 0 else 248
            pdf.set_fill_color(fill_color, fill_color, fill_color)

            for col in display_cols:
                raw_val = row.get(col, "")
                if isinstance(raw_val, float):
                    val_str = f"{raw_val:,.2f}"
                elif isinstance(raw_val, int):
                    val_str = f"{raw_val:,}"
                else:
                    val_str = str(raw_val)
                pdf.cell(col_w, 6, val_str, border=1, fill=True, align=align)
            pdf.ln()

    def _render_calculation_note(
        self,
        pdf: PDFReportDocument,
        note: str,
        language: str,
    ) -> None:
        """Render calculation description box."""
        pdf.ln(3)
        pdf.set_fill_color(241, 245, 249)
        pdf.set_draw_color(203, 213, 225)
        box_y = pdf.get_y()

        header_label = "طريقة الحساب:" if language == "ar" else "Calculation Methodology:"
        pdf.rect(10, box_y, 190, 16, style="DF")
        pdf.set_xy(14, box_y + 2)
        pdf.set_font(pdf.active_font, "B", 8)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(182, 4, header_label, align="R" if language == "ar" else "L")

        pdf.set_xy(14, box_y + 7)
        pdf.set_font(pdf.active_font, "", 8)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(182, 6, note[:180], align="R" if language == "ar" else "L")
        pdf.set_y(box_y + 18)
